### ISSUE TITLE
eager loading of relation

### ISSUE THREAD

**Issue by RoelandMatthijssens** [RoelandMatthijssens/shoppingList#11]
Do we want to load the full content of the list (eager loading) or just the IDs.

Just Ids:
  Benefits: Looks cleaner, less data transferred.
  Downside: More request needed to fetch purchase/item data.

Eager loaded:
  Benefits: No additional request needed for purchase fetching (still needed for item)
  Downside: Less clean, less restful.

**Comment by JeffreyVdb** [comment]
First one.
