### ISSUE TITLE
Purchase amounts

### ISSUE THREAD

**Issue by RoelandMatthijssens** [RoelandMatthijssens/shoppingList#12]
What database type does the amount of a purchase need to be? 
Semantically it means 'how many of the specific item are requested'
This works well in the case of simple items
```
{"item": "banana", "amount": 10}
```
Semantically this means i want 10 bananas.

But there are other situations where an integer field is not sufficient. 
```
{"item": "minced meat", "amount": 250}
```
Semantically this would mean i want 250gr of minced meat. But the `gr` is not specified.
Something like this would be cleaner
```
{"item": "minced meat", "amount": "250gr"}
```
But this means the `amount` field would just be free text. Which is not what we want.
Ideally i want to be able to prompt the user when he checks an item as purchased that he needs to make sure he buys the right `amount`. This is not possible when the amount is free text

**Comment by JeffreyVdb** [comment]
```{"item": "minced meat", "quantity": 1, "amount": "250gr"}```

Amount is free text, optional. 
Quantity is integer.
```{"item": "banana", "quantity": 10}```

Notification is set to quantity
